### ISSUE TITLE
failed to load with IDA 6.6

### ISSUE THREAD

**Issue by JohnWins** [keystone-engine/keystone#243]
Hi,

I have installed IDA 6.6 and 6.8, and it works fine with 6.8 but failed to load 6.6 version.
and here is a screenshot.

![ida6_6_failed](https://cloud.githubusercontent.com/assets/18698031/18821584/2f1ce27c-83da-11e6-945c-84fdc29ca87e.png)

**Comment by aquynh** [comment]
this should be reported as an issue of Keypatch at https://github.com/keystone-engine/keypatch, rather than Keystone?

you have this problem because Keystone binding (Python) cannot be seen by your IDA 6.6 for some reasons.

to fix this, you can do:

- install Keystone Python 0.9.1 32-bit from https://github.com/keystone-engine/keystone/releases/download/0.9.1/keystone-0.9.1-python-win32.msi
- copy the whole binding directory "keystone/" somewhere under c:\<python-dir> (find that yourself) to  `C:\Program Files (x86)\IDA 6.6\python\keystone`.
- double check that you have keystone.dll inside  `C:\Program Files (x86)\IDA 6.6\python\keystone`
- run IDA again now to see if Keypatch works.

**Comment by JohnWins** [comment]
Thanks for your info.
I have re-install it and copy keystone folder to python folder,
and it works now.

**Comment by aquynh** [comment]
so section https://github.com/keystone-engine/keypatch/blob/master/README.md#a1-windows should be improved. if you can, please send a pull req to do that, thanks.

**Comment by LittleSec** [comment]
I have a program "module 'keystone' has no attribute 'KS_ARCH_X86'", maybe you can see this https://docs.angr.io/introductory-errata/install
